version: '3.8'

services:
  myapp:
    image: regionquery:latest
    container_name: regionquery_container
    ports:
      - "5202:80"
    environment:
      ASPNETCORE_ENVIRONMENT: "HML"
    networks:
      - techchallengenetwork

networks:
  techchallengenetwork:
    external: true